services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  web:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    container_name: web-app
    ports:
      - "3001:3000"
    volumes:
      - ./web-app:/app
    depends_on:
      - mongodb
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped

  web-tests:
    build:
      context: ./web-app
      dockerfile: Dockerfile.test
    container_name: web-tests
    depends_on:
      - mongodb
    command: ["pytest", "--tb=short", "--maxfail=2", "--disable-warnings", "--cov=app", "tests/"]
    volumes:
      - ./web-app:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: "no"

volumes:
  mongo-data: