services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  web:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    container_name: web_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./web_app/uploads:/app/uploads
    depends_on:
      - mongodb
    environment:
      - FLASK_APP=web_app.app:create_app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MONGO_URI=mongodb://mongodb:27017/gameforum
    restart: unless-stopped

  web-tests:
    build:
      context: ./web_app
      dockerfile: Dockerfile.test
    container_name: web-tests
    depends_on:
      - mongodb
    command: ["pytest", "--tb=short", "--maxfail=2", "--disable-warnings", "--cov=web_app", "web_app/tests/"]
    volumes:
      - .:/app
    environment:
      - FLASK_APP=web_app.app:create_app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MONGO_URI=mongodb://mongodb:27017/gameforum
    restart: "no"

volumes:
  mongo-data:
