services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  web:
    build: ./web-app
    container_name: web-app
    ports:
      - "3001:3001"
    volumes:
      - ./web-app:/app
    depends_on:
      - mongodb
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped
    
  web-tests:
    build: ./web-app/tests  # Build from the test directory
    container_name: web-test
    depends_on:
      - mongodb
      - web
    command: ["pytest", "tests/"]  # Run the tests using pytest
    volumes:
      - ./web-app:/app  # Mount the web app directory into the container
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: "no" 
    
#  ml-tests:
#    build: ./machine-learning-client
#    depends_on:
#      - mongodb
#    command: ["pytest", "tests/"]
#    volumes:
#      - ./machine-learning-client:/app


volumes:
  mongo-data: