# web-app/Dockerfile.test

FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH=/app
ENV FLASK_APP=app
ENV FLASK_ENV=development
ENV FLASK_DEBUG=1

CMD ["pytest", "--tb=short", "--maxfail=2", "--disable-warnings", "--cov=app", "tests/"]